### ISSUE TITLE
Prototool options changing

### ISSUE THREAD

**Issue by peter-edge** [zvelo/msg#28]
Hi, I saw you're using some options we're removing in Prototool in preparation for Prototool v1.0, but you have no need for them, so just a heads up:

- `protoc_include_wkt` is going away and is the new default, so you can safely delete this setting.
- `lint.group` is going away, but you have it set as `default`, which is the only option, so you can safely delete this setting.
- `gen.go_options.no_default_modifiers` is going away, and all default modifiers will automatically be set. We already generate the modifiers you have set for the Well-Known Types in your `extra_modifiers` setting if the plugin type is `go` or`gogo` https://github.com/uber/prototool/blob/dev/internal/wkt/wkt.go#L62, so you should delete both `no_default_modifiers` and `extra_modifiers`. It's counterintuitive (and could be documented better, that's my fault) but if you really want to import the gogo/protobuf paths for the Well-Known Types for grpc-gatway, just set the type for grpc-gateway to `gogo`.

See https://github.com/uber/prototool/pull/162 for more details.

I also see in your code https://github.com/zvelo/msg/blob/master/magefile.go#L56 and https://github.com/zvelo/msg/blob/master/magefile.go#L90 you're calling `protoc` manually for two things Prototool is capable of :-) Let me know if you have any questions.

**Comment by joshuarubin** [comment]
Thanks for all the info.

Just to be clear, in other (private) repos, we have `extra_modifiers` beyond the `gogo` ones. This field will continue to work in this case?

**Comment by peter-edge** [comment]
Yep!
